name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: dropdown
    id: app
    attributes:
      label: Target App
      description: Which app would this feature be for?
      options:
        - apps/app (Dashboard)
        - apps/www (Marketing)
        - apps/docs (Documentation)
        - apps/legal (Legal)
        - packages/ui (Design System)
        - Multiple apps
        - New package/app
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      options:
        - New feature
        - Enhancement to existing feature
        - UI/UX improvement
        - Performance improvement
        - Developer experience
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear description of what the problem is. Ex. I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: A clear description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If applicable, add mockups, screenshots, or links to similar implementations.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.
